pipeline {
    agent any

    environment {
        JAVA_HOME  = tool 'JDK25'       // Nom JDK configuré dans Jenkins
        MAVEN_HOME = tool 'Maven_3.9'   // Nom Maven configuré dans Jenkins
        PATH       = "${JAVA_HOME}\\bin;${MAVEN_HOME}\\bin;%PATH%"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Dorra-testing/Seleniumwebdriver.git'
            }
        }

        stage('Build & Test') {
    steps {
        dir('SeleniumBDD') {
            bat 'java -version'
            bat 'mvn -version'
            bat 'mvn clean test -Dcucumber.options="--glue src/test/java --tags @YourTagName"'
        }
    }
}

        stage('Generate Report') {
            steps {
                // Publier les rapports HTML ExtentReports
                publishHTML(target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'SeleniumBDD/report/html',  // dossier du rapport généré
                    reportFiles: 'reportTest.html',        // fichier HTML principal
                    reportName: 'Extent Report'
                ])
            }
        }
    }

    post {
        always {
            echo 'Pipeline terminé'
        }
        failure {
            echo 'Pipeline échoué !'
        }
    }
}
